// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMtyvTs0MI3Nmc7XS616BvafEXsroDZHU',
    appId: '1:640364175281:web:37f3d91fa316c57a026790',
    messagingSenderId: '640364175281',
    projectId: 'nurseai-fdbf4',
    authDomain: 'nurseai-fdbf4.firebaseapp.com',
    storageBucket: 'nurseai-fdbf4.appspot.com',
    measurementId: 'G-S2LGW1KEWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByv_YjDgNn_I_PlEbo-vFrHVV8yFweG44',
    appId: '1:640364175281:android:a10b894e41b7dabb026790',
    messagingSenderId: '640364175281',
    projectId: 'nurseai-fdbf4',
    storageBucket: 'nurseai-fdbf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrvB0IOp5OVg4TIuib4-iHoAkJndcrd5g',
    appId: '1:640364175281:ios:ff31595113200490026790',
    messagingSenderId: '640364175281',
    projectId: 'nurseai-fdbf4',
    storageBucket: 'nurseai-fdbf4.appspot.com',
    iosBundleId: 'com.example.instagramCloneFlutter',
  );
}
